name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: printhello
        run: echo "Hello World!"

          - uses: actions/checkout@v1

              - name: Set Up JDK
                uses: actions/setup-java@v1
                with:
                  java-version: 1.8

              - name: Change wrapper permissions
                run: chmod +x ./gradlew

              - name: Run Tests
                run: ./gradlew test

              - name: Build Project
                run: ./gradlew build

              - name: Build Release AAB
                run: ./gradlew bundleRelease